# ---------------------------------------- #
#              DOCKER COMPOSE              #
# ---------------------------------------- #
#                  MYSQL 8                 #
# ---------------------------------------- #

version: '3.8'

services:
  db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: christian80gabi
      MYSQL_PASSWORD: christian80gabi.password
    ports:
      - 3306:3306
    volumes:
      - ./.data:/var/lib/mysql

volumes:
  data: { }

networks:
  default:
    name: mysql_default
