# ---------------------------------------- #
#              DOCKER COMPOSE              #
# ---------------------------------------- #
#            PotgreSQL + pgadmin           #
# ---------------------------------------- #

version: '3.8'

services:
  db:
    container_name: postgresql_db
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: christian80gabi
      POSTGRES_PASSWORD: christian80gabi.password
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: postgresql_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./.dbadmin/pgadmin:/var/lib/pgadmin
      # sudo chown -R 5050:5050 ./.dbadmin/
      # Use to give access to pgadmin to write on the repository ".dbadmin". Especially on Linux

volumes:
  data: { }

networks:
  default:
    name: postgresql_default